### ISSUE TITLE
Time parsing issue

### ISSUE THREAD

**Issue by tim-fitzgerald** [turbot/steampipe-plugin-linear#43]
**Describe the bug**
Running the example query returns an error:

`Error: linear: parsing time "2024-07-30" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T" (SQLSTATE HV000)`

**Steampipe version (`steampipe -v`)**
v0.23.3

**Plugin version (`steampipe plugin list`)**
v0.3.0

**To reproduce**
```sql
> select
  title,
  created_at,
  branch_name,
  priority
from
  linear_issue;
```

**Expected behavior**
issues are returned

**Additional context**

**Comment by tim-fitzgerald** [comment]
Setting todays date explicitly does not return the same error

```sql
 select created_at from linear_issue where created_at = '2024-07-30';
+------------+
| created_at |
+------------+
+------------+
```

But comparing it using any other comparator does

```sql
select created_at from linear_issue where created_at < '2024-07-30';

Error: linear: parsing time "2024-07-31" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T" (SQLSTATE HV000)

+------------+
| created_at |
+------------+
+------------+
```

**Comment by tim-fitzgerald** [comment]
Further discovery - this only happens on my company enterprise Workspace. Using a personal API key works just fine.

**Comment by tim-fitzgerald** [comment]
@ParthaI thanks for fixing this. 

Could you give me some context on what the issue was and how the fix was implemented? I had taken a good look at the code myself and could not spot what the problem was so super curious :)

**Comment by ParthaI** [comment]
Hi @tim-fitzgerald,

Here’s a summary of the issue and how we implemented the fix:

### Issue Explanation:
- In Steampipe tables, the `TIMESTAMP` column type by default converts the time value to the format `2006-01-02T15:04:05Z07:00`.
- The issue occurred when parsing a date value like `2024-07-30` into this timestamp layout. Since the incoming format didn’t include a time component, the layout mismatch caused the failure.

### Fix Implementation:
- We use the Go package [genqlient](https://github.com/Khan/genqlient) for constructing the GraphQL client API responses.
- I raised a support request to address this issue in the SDK we are using. Reference: [genqlient issue #345](https://github.com/Khan/genqlient/issues/345).
- Based on their feedback, I added an [unmarshal function](https://github.com/turbot/steampipe-linear-genqlient-formatter/blob/main/utils/format.go) to our schema to handle the data format we were receiving. You can find the reference [here](https://github.com/turbot/steampipe-plugin-linear/blob/main/gql/genqlient.yaml#L14-L19).
- To avoid a circular import issue, we created a separate repository/package specifically for handling the `UnmarshalDateTime` function.

These changes resolved the issue.

I hope this explanation helps clarify the problem and the solution we applied.

Thanks!
